name: Smarter Asp Deploy - Develop

on:
  push:
    branches: [ main ]

jobs:

  Build-Deploy:
    runs-on: windows-latest
    env:
      MSDEPLOY_PATH: "C:/Program Files/IIS/Microsoft Web Deploy V3/msdeploy.exe"
      MAIN_PROJ_PATH: "./src/Api/Api.csproj"
      SLN_PATH: "./src/AceleraDevTodoList.sln"
      PUBLISHED_PATH: "D:/a/todo-list-backend/todo-list-backend/src/Api/bin/Release/net8.0/publish"
      PARAMFILE_PATH: "D:/a/todo-list-backend/todo-list-backend/.github/parameters_develop.xml"
      IIS_SERVER_COMPUTER_NAME: ${{ secrets.SERVER_COMPUTER_NAME }}
      IIS_WEBSITE_NAME: ${{ secrets.WEBSITE_NAME }}
      IIS_SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      IIS_SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

    steps:
    - uses: actions/checkout@v2

    - name: "Check file existence"
      uses: andstor/file-existence-action@v1
      with:
        files: "${{ env.MSDEPLOY_PATH }}, ${{ env.MAIN_PROJ_PATH }}, ${{ env.SLN_PATH }}, ${{ env.PARAMFILE_PATH }}"
        allow_failure: true

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: dotnet restore
      run: dotnet restore ${{ env.SLN_PATH }}

    - name: dotnet build
      run: dotnet build ${{ env.SLN_PATH }} --configuration Release
        
    - name: dotnet publish
      run: dotnet publish ${{ env.MAIN_PROJ_PATH }} --configuration Release

    - name: "Check file existence - publish"
      uses: andstor/file-existence-action@v1
      with:
        files: "${{ env.PUBLISHED_PATH }}"
        allow_failure: true
    
    - name: Deploy Application
      shell: cmd
      run: | 
        "${{ env.MSDEPLOY_PATH }}" -source:iisApp="${{ env.PUBLISHED_PATH }}" -dest:auto,AuthType="Basic",IncludeAcls="False",ComputerName="${{ env.IIS_SERVER_COMPUTER_NAME }}",username="${{ env.IIS_SERVER_USERNAME }}",password="${{ env.IIS_SERVER_PASSWORD }}" -verb:sync -enableRule:AppOffline -disableLink:AppPoolExtension -disableLink:ContentExtension -disableLink:CertificateExtension -retryAttempts=10 -retryInterval=2000 -userAgent="VSCmdLine:WTE5.0.4.12324" -allowUntrusted -setParamFile:"${{ env.PARAMFILE_PATH }}" -skip:File="web.config" -skip:File="appsettings.Development.json" -skip:File="appsettings.Production.json" -skip:Directory=wwwroot -skip:Directory=logs -skip:Directory=".well-known"

